### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by IdanKoblik** [BETAIDK/BgBot#14]
### TODO:
- [x] Add endpoint that return http 200
- [x] Fix some titles
- [x] Polish the code before the final release

**Comment by IdanKoblik** [comment]
- [x] there is more sub event in the pipeline event, add them

**Comment by IdanKoblik** [comment]
- [x] Add emojis for the discord replays

**Comment by IdanKoblik** [comment]
Add command manager

**Comment by IdanKoblik** [comment]
Change the https://beta-gitlab.linuxwiz.net/webhook url to dont be hard coded
